### ISSUE TITLE
Maintain multiple processors

### ISSUE THREAD

**Issue by bjendres** [greenpeace-cee/at.greenpeace.donutapp#1]
I have added a different processor in [my fork](https://github.com/systopia/at.greenpeace.donutapp), and for the most part the changes are contained in the ``CRM/Donutapp/Processor/Naturherzen`` namespace, but there are some adjustments to the core extension as well.

I would like to talk about:
- if we can merge the changes to the common part
- whether and how we could sustain and manage multiple processors within the same repository, or what other options we have

**Comment by pfigel** [comment]
The core changes look reasonable at a quick glance. I'd be okay with using one repository - if it becomes a maintenance problem in the future, we could think about a plugin approach where the processors are in separate repos, but I don't imagine that would be necessary any time soon.

Will discuss this with the team and get back to you once we've agreed on something.

**Comment by bjendres** [comment]
> The core changes look reasonable at a quick glance. I'd be okay with using one repository

Cool, I'll create a PR then.

>  - if it becomes a maintenance problem in the future, we could think about a plugin approach where the processors are in 
> separate repos, but I don't imagine that would be necessary any time soon.

The more I think about it the more I would favour using the plugin approach right away. That gives you the freedom to maintain your own extension (including the GP processor code if you want), without having to accept pull requests every time anybody wants a little change in their processing.

**Comment by pfigel** [comment]
This was merged with #5, thanks @bjendres!
